name: Complete Workflow

on: ['push']

jobs:

  build:

    runs-on: ubuntu-latest

    stategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Use NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Start MondoDB
      uses: supercharge/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      run: yarn --frozen-lockfile
      run: yarn test
